name: UX Revolution
favicon: null
layout_spectrum: 0.40991541161201894
typography_spectrum: 0.09943
title: UX Revolution
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cde5e1'
    - '#383838'
    - '#00ffff'
    - '#0000ff'
    - '#939091'
  brandStrength: 1
  lightness: 0.997503689257428
  saturation: 0.4104692523833364
  rhythmicContrast: 0.6397632015869021
purpose: []
